### ISSUE TITLE
Frequent crashes when using in a Default world (ASMTick)

### ISSUE THREAD

**Issue by tripl3dogdare** [Cubitect/ASMModSuit#2]
The crash appears to be caused when moving quickly (i.e. flying in creative) towards unloaded chunks. Possibly an issue with handling large amounts of tile ticks at once, or not-yet-valid tile ticks being picked up?

[crash-2016-09-30_10.24.55-client.txt](https://github.com/Cubitect/ASMModSuit/files/503395/crash-2016-09-30_10.24.55-client.txt)

**Comment by Cubitect** [comment]
Thanks for reporting. Is this still an issue? 
I just added a try catch around the tile-tick managing, so its not a very good fix, but it should work.

**Comment by tripl3dogdare** [comment]
That appears to have solved the problem!
