### ISSUE TITLE
Does not work at all!

### ISSUE THREAD

**Issue by OscRos03** [Cubitect/ASMModSuit#6]
When I try to install the mods it fails. The console says: 

Preparing directory tree for client...

Searching for mappings for ASMVillageMarker...
404: ASMRender
Setting up ASMRender...
Main -> net/minecraft/client/main/Main
MinecraftServer -> net/minecraft/server/MinecraftServer
Disassembeling net/minecraft/client/main/Main...
'C:/Program' is not recognized as an internal or external command, operable program or batch file.

And the error message says:

[Errno 2] No such file or directory:
u'C:\\WINDOWS\\system32\\1.11.2\\jarasm/net/minecraft/client/main/Main,j'

This is when I only try to install the village marker

I have no idea what this means but hopefully someone does and knows how to fix it. Comment if you need any additional info!

**Comment by jimvanderveen** [comment]
Were you able to solve this @OscRos03 ? If so, what did you do?
